spring.application.name=java_task
spring.datasource.url=jdbc:postgresql://localhost:5432/nazwa_twojej_bazy
spring.datasource.username=e_commerce
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update